### 회원가입 요청
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "nickname" : "test01",
  "email" : "test01@gmail.com",
  "password" : "111111"
}

### 로그인 요청
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
"email" : "test01@gmail.com",
"password" : "111111"
}
