### create errand (사진 첨부 있는 경우)
POST http://localhost:8080/errands
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MDFAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTY5MTEyMDk1MywiZXhwIjoxNjkxMTQyNTUzfQ.5RSvSqdfREtkn_Sye_X9UfpMsnr8WvUPML0oBhMn258
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="errand";
Content-Type: application/json

{
"title" : "제목입니다.",
"content" : "내용입니다.",
"payDivision" : "HOURLY",
"pay" : 10000
}
--WebAppBoundary--
Content-Disposition: form-data; name="images"; filename="image.txt"
Content-Type: multipart/form-data

IMAGE
--WebAppBoundary

### create errand (사진 첨부 없는 경우)
POST http://localhost:8080/errands
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MDFAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTY5MTEyMDk1MywiZXhwIjoxNjkxMTQyNTUzfQ.5RSvSqdfREtkn_Sye_X9UfpMsnr8WvUPML0oBhMn258
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="errand";
Content-Type: application/json

{
"title" : "제목입니다.",
"content" : "내용입니다.",
"payDivision" : "HOURLY",
"pay" : 10000
}
--WebAppBoundary

### getErrand (의뢰 단건 조회)
GET http://localhost:8080/errands/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MDFAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTY5MTEyMDk1MywiZXhwIjoxNjkxMTQyNTUzfQ.5RSvSqdfREtkn_Sye_X9UfpMsnr8WvUPML0oBhMn258

### addHashtag
### create errand
PUT http://localhost:8080/errands/1/hashtag?tag="영상편집"
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MDFAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTY5MTEyMDk1MywiZXhwIjoxNjkxMTQyNTUzfQ.5RSvSqdfREtkn_Sye_X9UfpMsnr8WvUPML0oBhMn258

### deleteHashtag
### create errand
DELETE http://localhost:8080/errands/1/hashtag?tag="영상편집"
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MDFAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTY5MTEyMDk1MywiZXhwIjoxNjkxMTQyNTUzfQ.5RSvSqdfREtkn_Sye_X9UfpMsnr8WvUPML0oBhMn258




